name: Continuous Integration

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip, wheel, pytest, jupyter
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install pytest
        pip install pytest-cov
        pip install jupyter
        pip install pyqsp

    - name: Install q.chem backend
      run: |
        pip install pyscf

    - name: Install backends except qsharp/qdk
      run: |
        pip install qiskit
        pip install qiskit_aer
        pip install qulacs
        pip install amazon-braket-sdk
        pip install cirq
        pip install projectq
        pip install pennylane
      if: always()

    - name: Install Microsoft qsharp/qdk
      run: |
        wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        rm packages-microsoft-prod.deb
        sudo apt-get update; sudo apt-get install -y apt-transport-https && sudo apt-get update
        sudo apt-get install -y dotnet-sdk-5.0
        dotnet tool install -g Microsoft.Quantum.IQSharp
        $(which dotnet-iqsharp) install --user
        pip install qsharp
      if: always()

    - name: tangelo install
      run: |
        pip install git+https://github.com/goodchemistryco/Tangelo.git@develop
      if: always()

    - name: Download required data to run the iFCI - MIFNO notebook
      run: |
        cd examples/problem_decomposition
        sudo apt-get install subversion
        svn export https://github.com/goodchemistryco/Tangelo/branches/develop/tangelo/problem_decomposition/tests/incremental/data/BeH2_CCPVDZ_MIFNO_HBCI
      if: always()

    - name: tangelo notebooks as tests
      run: |
        cd examples
        pytest --doctest-modules --junitxml=junit/notebook-test-results.xml test_notebooks.py
      if: always()

    - name: Upload pytest test results
      uses: actions/upload-artifact@v3
      with:
        name: notebook-test-results
        path: examples/junit/notebook-test-results.xml

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
      if: always()
